### ISSUE TITLE
Incorrect link on novapackages

### ISSUE THREAD

**Issue by LorenzoSapora** [dddeeemmmooonnn/nova-multicolumn-filter#1]
On your [novapackages page](https://novapackages.com/packages/dddeeemmmooonnn/nova-multicolumn-filter) for this repo, you have entered the link incorrectly, missing out the final "r" in "filter".

Current link

`https://github.com/dddeeemmmooonnn/nova-multicolumn-filte`

Should be:

`https://github.com/dddeeemmmooonnn/nova-multicolumn-filter`

**Comment by dddeeemmmooonnn** [comment]
Thanks!
