### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by ArtMin96** [dddeeemmmooonnn/nova-multicolumn-filter#12]
Hi.

It's not a bug report, just want to ask how can we use the filters?
Like I'm new in nova and I'm confused.

Where do I need to put this kind of code?

new NovaMulticolumnFilter([
        'column' => '', //columns
    ],
    $manual_update = false, // Apply filter with the button
    $default_column_type = 'text', // Default input type
    $name = 'filter' // Filter name
), 

or if I wanna create a new one how can I use it?

**Comment by rajathans** [comment]
hey @ArtMin96 were you able to figure it out?

**Comment by ArtMin96** [comment]
> hey @ArtMin96 were you able to figure it out?

No

**Comment by dddeeemmmooonnn** [comment]
Nova has pretty clear documentation https://nova.laravel.com/docs/3.0/filters/registering-filters.html

put this code in `filters` method in your resource class
```
public function filters(Request $request)
{
    return [
        new NovaMulticolumnFilter(
            [
                'column' => '', //columns
            ],
            $manual_update = false, // Apply filter with the button
            $default_column_type = 'text', // Default input type
            $name = 'filter' // Filter name
        ),
    ];
}
```
