### ISSUE TITLE
'Add' button isn't adding a new filter

### ISSUE THREAD

**Issue by thiskbj** [dddeeemmmooonnn/nova-multicolumn-filter#2]
When I click the 'add' button, it's just closing the filter popup, rather than adding a way to add a new filter. This is Nova version 2.5.0.

**Comment by thiskbj** [comment]
Adding - looks like I can't use this until it's fixed, since the filter won't apply. Any ideas?

**Comment by dddeeemmmooonnn** [comment]
I'll see now

**Comment by thiskbj** [comment]
Thanks. Any leads? In the meantime I'm trying the original column filter.

**Comment by dddeeemmmooonnn** [comment]
fixed in 0.4.1, try
problem in nova changes https://github.com/laravel/nova-issues/issues/2083

**Comment by thiskbj** [comment]
Yay, that works!! Thank you so much! :)
