### ISSUE TITLE
[Question] Implementation of `whereIn` operator

### ISSUE THREAD

**Issue by bilfeldt** [dddeeemmmooonnn/nova-multicolumn-filter#3]
I am trying to figure out how to implement the eloquent method `whereIn` in combination with an input field where the input is split by some delimiter.

Imagine a filter like so:

- Field: `id`
- Operator: `in`
- Value: `"1,2,3"`

which would add the following query:
```php
$query->whereIn('id', [1, 2, 3]);
```
where the array of id's are retrieved as
```php
$values = explode($delimiter=',', $value);
```

This would make it possible to filter a resource based on an array of id's for example.

Do you have any pointers as how to implement something like this using your package? Thanks.

**Comment by dddeeemmmooonnn** [comment]
Hello.
You can extend `dddeeemmmooonnn\NovaMulticolumnFilter\NovaMulticolumnFilter` and override `apply` method

**Comment by bilfeldt** [comment]
True, but that would require me to override the `apply` method, which will break in case of future field types being implemented.

Are you open for a PR for this operator? Or alternatively, might I suggest refactoring the `apply` method to use a new `applySingle` in the `foreach (json_decode($value, true) as $val) {}` loop. In that case, people can simply extend the `applySingle` method to call their own method if a custom filter is provided and otherwise the parent `applySingle`.

**Comment by dddeeemmmooonnn** [comment]
I think then it is better to add a new option for the column - the name of the method by which to process the column.
Then you will need to add the method and specify it in the options
I'll do it later today

ofc open for PR

**Comment by bilfeldt** [comment]
@dddeeemmmooonnn that would be a nice refactoring. When added please let me know and I will check if I can implement this feature, hopefully as a PR. I think it would be a neat addon 👍

**Comment by dddeeemmmooonnn** [comment]
0.5 update
