### ISSUE TITLE
How can we change placeholder of box?

### ISSUE THREAD

**Issue by hiren-dynamo** [dddeeemmmooonnn/nova-multicolumn-filter#4]
Thanks for the great customized option of all types of filters.
If we have to change the placeholder of the text box and select instead of "--" then how can we do?

Second Question: 
Initially display the "Add" button can we display the first filter directly? 

And any way to change the "Add" button text when no filter added? After adding one filter "Add" button text is Ok

**Comment by dddeeemmmooonnn** [comment]
Added placeholder, default null option, translations
