### ISSUE TITLE
The select field stays empty when the option has accents

### ISSUE THREAD

**Issue by jlballes** [dddeeemmmooonnn/nova-multicolumn-filter#6]
Hi,
I have a filter with this column:

`protected $columns = [
        'province' => [
            'type' => 'select',
            'options' => [
                'Almería' => 'Almería',
                'Madrid' => 'Madrid',
                'Ciudad Real' => 'Ciudad Real'
             ],
            'label' => 'Province',
        ]
    ];`

When I select 'Madrid' the select field shows 'Madrid', but if I select an option with accents or blanks like 'Almería' or 'Ciudad Real', the select field shows empty, although the data is filtered correctly.
The problem is that the user does not know what option has selected.

Best regards and thank you for this Nova package.

**Comment by dddeeemmmooonnn** [comment]
thx, fixed
